### ISSUE TITLE
Null pointer exception when a release definition has less than 2 releases 

### ISSUE THREAD

**Issue by manupaisable** [elrob/build-mon#6]

**Comment by elrob** [comment]
Thanks for spotting this issue.
This is fixed in the latest commit: 23f89f02b341965a1b5584d69815e9b23f463345

@rufusraghunath might be interested in this update

**Comment by rufusraghunath** [comment]
Thanks for opening this issue Manuel!

**Comment by manupaisable** [comment]
You're welcome @rufusraghunath . Thanks for the quick fix @elrob.

I'll work on a pull request to enable filtering build definitions by name pattern, as that is another problem I've come across using the tool (with a large set of build definitions in the same project)
